spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: bmw-sales-gateway
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

# 网关配置

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000 
    
swagger.enabled: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:        
    bmw-sm-service:
        path: /sm/**
        serviceId: bmw-sm
        stripPrefix: false
        sensitiveHeaders:
    bmw-stock-service:
        path: /stock/**
        serviceId: bmw-stock
        stripPrefix: false
        sensitiveHeaders:
    bmw-contract-service:
        path: /contract/**
        serviceId: bmw-contract
        stripPrefix: false
        sensitiveHeaders:
    bmw-contract-template-service:
        path: /contract-template/**
        serviceId: bmw-contract-template
        stripPrefix: false
        sensitiveHeaders:
    bmw-retail-service:
        path: /retail/**
        serviceId: bmw-retail
        stripPrefix: false
        sensitiveHeaders:
---

spring:
  profiles: k8s
  application:
    name: bmw-sales-gateway
server:
  port: 9000


eureka:
  client:
    service-url:
      defaultZone: http://bmw-register:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

# 网关配置

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000 
    
swagger.enabled: true

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:      
    bmw-sm-service:
        path: /sm/**
        serviceId: bmw-sm
        stripPrefix: false
        sensitiveHeaders:
    bmw-stock-service:
        path: /stock/**
        serviceId: bmw-stock
        stripPrefix: false
        sensitiveHeaders:
    bmw-contract-service:
        path: /contract/**
        serviceId: bmw-contract
        stripPrefix: false
        sensitiveHeaders:
    bmw-contract-template-service:
        path: /contract-template/**
        serviceId: bmw-contract-template
        stripPrefix: false
        sensitiveHeaders:
    bmw-retail-service:
        path: /retail/**
        serviceId: bmw-retail
        stripPrefix: false
        sensitiveHeaders:
    bmw-order-service:
        path: /order/**
        serviceId: bmw-order
        stripPrefix: false
        sensitiveHeaders:
    bmw-model-service:
        path: /model/**
        serviceId: bmw-model
        stripPrefix: false
        sensitiveHeaders:
    bmw-sales-dashboard-service:
        path: /sales-dashboard/**
        serviceId: bmw-sales-dashboard
        stripPrefix: false
        sensitiveHeaders:
